### PR TITLE
Update build.yml Node versions and remove redundant git submodules command

### PR DESCRIPTION
**Pull request by Mukul1127**
The title sums it up

### CODE REVIEW

**Comment by Mukul1127** [comment]
It keeps failing on `RectifyControlPanel2`

**Comment by MishaProductions** [comment]
that's because the dui70 submodule in the rectifycontrolpanel2 submodule isn't being cloned for some reason

**Comment by Mukul1127** [comment]
> that's because the dui70 submodule in the rectifycontrolpanel2 submodule isn't being cloned for some reason

The submodules parameter need to be recursive, fixed it

**Comment by MishaProductions** [comment]
Thanks for the PR!

**Pull request merged**
